runtime: python39 # or whatever your Python version is
entrypoint: gunicorn -b :$PORT wsgi:app # replace 'app:app' with '<your python file without .py>:app'

instance_class: F4

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1
